# Generated by Django 2.2.5 on 2019-11-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(default='Professor', max_length=60),
        ),
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.CharField(default='Score', max_length=30),
        ),
        migrations.AlterField(
            model_name='score',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professors', to='crud.Professor'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='crud.Student'),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Student', max_length=60),
        ),
    ]
